👷 [Ci] qa 환경 서버 배포 설정

diff --git a/.github/workflows/deploy-qa.yml b/.github/workflows/deploy-qa.yml
--- a/.github/workflows/deploy-qa.yml
+++ b/.github/workflows/deploy-qa.yml
@@ -1,10 +1,9 @@
-name: Gamegoo Socket Server DEV CI/CD
+name: Gamegoo Socket Server QA CI/CD
 
 on:
-  pull_request:
-    types: [closed]
+  push:
     branches:
-      - develop
+      - qa
   workflow_dispatch: # 수동 실행 가능하도록
 
 jobs:
@@ -13,13 +12,14 @@ jobs:
 
     env:
       JWT_SECRET: ${{ secrets.JWT_SECRET }}
-      SOCKETIO_URL: ${{ secrets.DEV_SOCKETIO_URL }}
-      API_SERVER_URL: ${{ secrets.DEV_API_SERVER_URL }}
-      NODE_SERVER_URL: ${{ secrets.DEV_NODE_SERVER_URL }}
+      SOCKETIO_URL: ${{ secrets.QA_SOCKETIO_URL }}
+      API_SERVER_URL: ${{ secrets.QA_API_SERVER_URL }}
+      NODE_SERVER_URL: ${{ secrets.QA_NODE_SERVER_URL }}
       DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
       DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
-      EC2_HOST: ${{ secrets.DEV_EC2_HOST }}
+      EC2_HOST: ${{ secrets.QA_EC2_HOST }}
       EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
+      EC2_LOG_PATH: ${{ secrets.EC2_LOG_PATH }}
 
     steps:
       # 1) GitHub checkout
@@ -52,9 +52,9 @@ jobs:
         uses: docker/build-push-action@v6
         with:
           context: .
-          file: ./Dockerfile-dev
+          file: ./Dockerfile-qa
           push: true
-          tags: ${{ env.DOCKERHUB_USERNAME }}/gamegoo-socket-dev:${{ github.sha }}
+          tags: ${{ env.DOCKERHUB_USERNAME }}/gamegoo-socket-qa:${{ github.sha }}
           platforms: linux/amd64
           build-args: |
             JWT_SECRET=${{ env.JWT_SECRET }}
@@ -73,30 +73,31 @@ jobs:
           script_stop: true # 스크립트 실패 시 중단
           script: |
             echo "Stopping existing container..."
-            docker stop gamegoo-socket-dev || true
+            docker stop gamegoo-socket-qa || true
             echo "Removing existing container..."
-            docker rm gamegoo-socket-dev || true
+            docker rm gamegoo-socket-qa || true
 
             echo "Pulling new Docker image..."
-            docker pull ${{ env.DOCKERHUB_USERNAME }}/gamegoo-socket-dev:${{ github.sha }}
+            docker pull ${{ env.DOCKERHUB_USERNAME }}/gamegoo-socket-qa:${{ github.sha }}
 
             echo "Running new Docker container..."
             docker run -d -p 3000:3000 \
-              --name gamegoo-socket-dev \
+              --name gamegoo-socket-qa \
+              -v ${{ env.EC2_LOG_PATH }}:/app/logs \
               -e JWT_SECRET=${{ env.JWT_SECRET }} \
               -e SOCKETIO_URL=${{ env.SOCKETIO_URL }} \
               -e API_SERVER_URL=${{ env.API_SERVER_URL }} \
               -e NODE_SERVER_URL=${{ env.NODE_SERVER_URL }} \
-              ${{ env.DOCKERHUB_USERNAME }}/gamegoo-socket-dev:${{ github.sha }}
+              ${{ env.DOCKERHUB_USERNAME }}/gamegoo-socket-qa:${{ github.sha }}
 
-      # 실패 시 디스코드에 알림 보내기
-      - name: 배포 실패 시 디스코드 알림 전송
-        if: failure() # 이전 스텝이 실패한 경우에만 실행
-        run: |
-          PR_NUMBER="${{ github.event.pull_request.number }}"
-          PR_TITLE="${{ github.event.pull_request.title }}"
-          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
-          PR_URL="${{ github.event.pull_request.html_url }}"
-          curl -X POST -H "Content-Type: application/json" \
-          -d "{\"content\": \"🚨 **Gamegoo Socket DEV 서버 배포 실패** 🚨\nPR 번호: ${PR_NUMBER}\nPR 제목: ${PR_TITLE}\nPR 작성자: ${PR_AUTHOR}\n[PR 보기](${PR_URL})\"}" \
-          $DISCORD_WEBHOOK_URL
+      # # 실패 시 디스코드에 알림 보내기
+      # - name: 배포 실패 시 디스코드 알림 전송
+      #   if: failure() # 이전 스텝이 실패한 경우에만 실행
+      #   run: |
+      #     PR_NUMBER="${{ github.event.pull_request.number }}"
+      #     PR_TITLE="${{ github.event.pull_request.title }}"
+      #     PR_AUTHOR="${{ github.event.pull_request.user.login }}"
+      #     PR_URL="${{ github.event.pull_request.html_url }}"
+      #     curl -X POST -H "Content-Type: application/json" \
+      #     -d "{\"content\": \"🚨 **Gamegoo Socket QA 서버 배포 실패** 🚨\nPR 번호: ${PR_NUMBER}\nPR 제목: ${PR_TITLE}\nPR 작성자: ${PR_AUTHOR}\n[PR 보기](${PR_URL})\"}" \
+      #     $DISCORD_WEBHOOK_URL
